version: '3.7'

services:
  app:
    env_file: .env
    build:
      context: ./docker
      dockerfile: Dockerfile.local
    volumes:
      - .:/var/www
    ports:
      - "8080:8080"
    external_links:
      - redis
      - mysql-8.0:db
    networks:
      - default
      - external-services

networks:
  external-services:
    external: true
