version: '3.3'

services:
  app:
    env_file: .env
    build: .
    volumes:
      - .:/var/www
      - /opt/gbv_uploads:/opt/gbv_uploads
    external_links:
      - redis
      - mysql-5.7:db
    restart: always
    networks:
      - default
      - external-services
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
      - /opt/gbv_uploads:/opt/gbv_uploads
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always

networks:
  external-services:
    external: true
