version: '3.7'

services:
  mysql:
    container_name: mysql-8.0
    image: mysql:8.0
    env_file: .env
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - external-services

networks:
  external-services:
    external: true
volumes:
  mysql-data:
    name: mysql-data

