version: '3.7'

services:
  mysql:
    container_name: mysql-8.0
    image: mysql:8.0
    env_file: .env
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - external-services
  solr:
    container_name: solr-9.5
    image: solr:9.5
    env_file: .env
    volumes:
      - solr-data:/var/solr
    restart: always
    command:
      - solr-precreate
      - gbv
networks:
  external-services:
    external: true
volumes:
  mysql-data:
    name: mysql-data
  solr-data:
    name: solr-data

