version: '3.4'

services:
  mysql:
    container_name: mysql-5.7
    image: mysql:5.7
    env_file: .env
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
volumes:
  mysql-data:
    name: mysql-data
