<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter()or tools and resource create form.
 */
function gbv_hooks_form_node_tools_and_resources_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'gbv_hooks/tools_resources';
}

/**
 * Implements hook_form_alter() for tools and resource edit form.
 */
function gbv_hooks_form_node_tools_and_resources_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'gbv_hooks/tools_resources';
}

/**
 * Implements hook_form_alter() for thematic area filter.
 */
function gbv_hooks_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (array_key_exists('field_thematic_resource_type_sec_target_id', $form)) {
    $form['#attached']['library'][] = 'gbv_hooks/thematic_filter';
  }

  if ($form["#id"] == "views-exposed-form-help-desk-view-help-desk-view") {
    $field_lang_id = 'field_language_target_id';
    $field_tools_resources_for_themat_id = 'term_node_tid_depth_1';
    $query = \Drupal::entityQueryAggregate('node')
      ->condition('status', 1)
      ->condition('type', 'tools_and_resources')
      ->condition('field_thematic_resource_type_sec', 120)
      ->groupBy('field_tools_resources_for_themat')
      ->groupBy('field_language');
    $results = $query->execute();
    $selected_tools_resources_for_themat = array_filter(array_unique(array_column($results, 'field_tools_resources_for_themat_target_id')));
    $selected_language = array_filter(array_unique(array_column($results, 'field_language_target_id')));
    $form[$field_tools_resources_for_themat_id]['#options'] = array_intersect_key($form[$field_tools_resources_for_themat_id]['#options'], array_flip($selected_tools_resources_for_themat));
    $form[$field_lang_id]['#options'] = array_intersect_key($form[$field_lang_id]['#options'], array_flip($selected_language));
  }
}
